### ISSUE TITLE
Should mypy be added to dev deps?

### ISSUE THREAD

**Issue by korikuzma** [GenomicMedLab/software-templates#15]
I think therapy normalizer is the only project that uses mypy. Should we add mypy to our other python projects for consistency?

**Comment by jsstevenson** [comment]
A few stray thoughts 

- I think many of our type errors would elude type checks because we use so many collection types (eg dicts, triples). I think there are strictness checks you can enforce so that you have to exhaustively define things but that might take some time to catch up to.
- some people prefer pyright. Some people just roll both since they aren't mutually exclusive and each has their own strengths. 
- The way VRS is structured, especially VRS 2, is really annoying for type checking, because so many attributes can either be an ID/reference or an actual object, but at runtime we tend to assume that the full object is there. Pyright/mypy light up on projects like the mave mapping lib because of this. So for projects that deal with VRS or sequence type objects you're signing up for a lot of 'type: ignore's, which starts to beg the question of how helpful it is to run the checks in the first place.

Personally, I have pyright running in my editor (anyone with VScode probably has it or Pylance as well) and I use it as insights to flag possible errors, but I haven't been in any rush to push for expanding our mypy usage beyond therapy (have thought about removing it to be consistent tbh)

**Comment by korikuzma** [comment]
I think we can close this. We can re-open if we'd like to add it in the future.
